# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='firstMeal',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastMeal',
        ),
        migrations.AddField(
            model_name='booking',
            name='first_meal',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='LUNCH', help_text='First Meal', max_length=1, verbose_name='First meal at camp'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_meal',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='LUNCH', help_text='Last Meal', max_length=1, verbose_name='Last meal at camp'),
        ),
    ]
