# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20160320_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetail',
            name='is_first_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='is_last_day',
            field=models.BooleanField(default=False),
        ),
    ]
