# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20160322_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetail',
            old_name='camp',
            new_name='camps',
        ),
        migrations.RenameField(
            model_name='reservationdetail',
            old_name='guide',
            new_name='guides',
        ),
    ]
