# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20160324_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetail',
            old_name='camp',
            new_name='camps',
        ),
        migrations.RenameField(
            model_name='reservationdetail',
            old_name='guide',
            new_name='guides',
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='is_first_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='is_last_day',
            field=models.BooleanField(default=False),
        ),
    ]
