# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20160324_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='sleeps',
            field=models.IntegerField(default=1, help_text='Sleeps how many'),
        ),
    ]
