# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20160331_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sleeping', models.PositiveSmallIntegerField(default=1, help_text='How many here tonight?')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Camp')),
                ('reservationdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ReservationDetail')),
            ],
        ),
        migrations.CreateModel(
            name='GuideDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Guide')),
                ('reservationdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ReservationDetail')),
            ],
        ),
    ]
