# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20160402_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidedetail',
            old_name='reservationdetail',
            new_name='reservation_detail',
        ),
    ]
