# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_auto_20160408_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetail',
            old_name='day',
            new_name='day_reserved',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='sleeps',
        ),
        migrations.RemoveField(
            model_name='campdetail',
            name='number_sleeping',
        ),
        migrations.AddField(
            model_name='camp',
            name='num_beds',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of beds'),
        ),
        migrations.AddField(
            model_name='campdetail',
            name='num_beds_used',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of beds being used'),
        ),
        migrations.AddField(
            model_name='campdetail',
            name='num_guests_staying',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of guests staying here'),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='eating_breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='eating_dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='eating_lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='num_beds_required',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of beds required'),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='num_guests',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of guests'),
        ),
        migrations.AlterField(
            model_name='reservationdetail',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation', unique_for_date='day_reserved'),
        ),
    ]
