# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_reservationdetail_num_guides_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetail',
            name='camps',
            field=models.ManyToManyField(to='bookings.Camp', unique_for_date='day_reserved'),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='num_guides',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
