# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20160308_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specific',
            name='guide',
        ),
        migrations.AddField(
            model_name='specific',
            name='guide',
            field=models.ManyToManyField(to='bookings.Guide'),
        ),
        migrations.AlterField(
            model_name='specific',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation', unique_for_date='day'),
        ),
    ]
