# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_camp_sleeps'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 30, 19, 9, 55, 888362, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='edited_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 30, 19, 10, 5, 607211, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
