# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20160330_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='sleeps',
            field=models.PositiveSmallIntegerField(default=1, help_text='Sleeps how many'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of Guests in Party'),
        ),
    ]
