# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_campdetail_guidedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdetail',
            name='camps',
        ),
        migrations.RemoveField(
            model_name='reservationdetail',
            name='guides',
        ),
        migrations.RemoveField(
            model_name='campdetail',
            name='camp',
        ),
        migrations.AddField(
            model_name='campdetail',
            name='camp',
            field=models.ManyToManyField(to='bookings.Camp'),
        ),
        migrations.RemoveField(
            model_name='guidedetail',
            name='guide',
        ),
        migrations.AddField(
            model_name='guidedetail',
            name='guide',
            field=models.ManyToManyField(to='bookings.Guide'),
        ),
    ]
