# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_auto_20160402_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='campdetail',
            name='reservationdetail',
        ),
        migrations.RemoveField(
            model_name='guidedetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guidedetail',
            name='reservation_detail',
        ),
        migrations.RemoveField(
            model_name='reservationdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservationdetail',
            name='reservation',
        ),
        migrations.AddField(
            model_name='campdetail',
            name='reservationdetail_ptr',
            field=models.OneToOneField(auto_created=True, default=27, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.ReservationDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidedetail',
            name='reservationdetail_ptr',
            field=models.OneToOneField(auto_created=True, default=27, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.ReservationDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='reservation_ptr',
            field=models.OneToOneField(auto_created=True, default=27, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.Reservation'),
            preserve_default=False,
        ),
    ]
