# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_auto_20160402_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campdetail',
            name='reservationdetail_ptr',
        ),
        migrations.RemoveField(
            model_name='guidedetail',
            name='reservationdetail_ptr',
        ),
        migrations.RemoveField(
            model_name='reservationdetail',
            name='reservation_ptr',
        ),
        migrations.AddField(
            model_name='campdetail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campdetail',
            name='reservationdetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.ReservationDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidedetail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidedetail',
            name='reservation_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.ReservationDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation', unique_for_date='day'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='campdetail',
            name='camp',
        ),
        migrations.AddField(
            model_name='campdetail',
            name='camp',
            field=models.ManyToManyField(to='bookings.Camp'),
        ),
        migrations.RemoveField(
            model_name='guidedetail',
            name='guide',
        ),
        migrations.AddField(
            model_name='guidedetail',
            name='guide',
            field=models.ManyToManyField(to='bookings.Guide'),
        ),
    ]
