# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_auto_20160402_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campdetail',
            old_name='reservationdetail',
            new_name='reservation_detail',
        ),
    ]
