# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_auto_20160402_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_beds',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of Beds required'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrival',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
