# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_auto_20160408_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='first_meal',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_meal',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='num_beds',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='party_size',
        ),
    ]
