# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_auto_20160408_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetail',
            name='num_guides_required',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of guides requested'),
        ),
    ]
