# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Booking ID'),
        ),
    ]
