# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.IntegerField(default=1, help_text='Number of Guests in Party')),
                ('arrival', models.DateField(default=datetime.date.today, help_text='Arrival Date')),
                ('departure', models.DateField(default=datetime.date.today, help_text='Arrival Date')),
                ('firstMeal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='LUNCH', help_text='First Meal', max_length=1)),
                ('lastMeal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='LUNCH', help_text='Last Meal', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Member'),
        ),
    ]
