# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Camp')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Guide')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation')),
            ],
        ),
    ]
