# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_day_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day_Detail',
            new_name='Specific',
        ),
    ]
