# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20160308_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specific',
            name='camp',
        ),
        migrations.AddField(
            model_name='specific',
            name='camp',
            field=models.ManyToManyField(to='bookings.Camp'),
        ),
    ]
