# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20160308_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('camp', models.ManyToManyField(null=True, to='bookings.Camp')),
            ],
        ),
        migrations.RemoveField(
            model_name='specific',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='specific',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='specific',
            name='reservation',
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['arrival']},
        ),
        migrations.AlterUniqueTogether(
            name='guide',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.DeleteModel(
            name='Specific',
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='guide',
            field=models.ManyToManyField(null=True, to='bookings.Guide'),
        ),
        migrations.AddField(
            model_name='reservationdetail',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation', unique_for_date='day'),
        ),
    ]
